import urllib.request
from datetime import date

# Translation Dictionaries
MONTHS_IS = {
    1: "janúar", 2: "febrúar", 3: "mars", 4: "apríl", 5: "maí", 6: "júní",
    7: "júlí", 8: "ágúst", 9: "september", 10: "október", 11: "nóvember", 12: "desember"
}

DAYS_IS = {
    "Monday": "mánudagur", "Tuesday": "þriðjudagur", "Wednesday": "miðvikudagur",
    "Thursday": "fimmtudagur", "Friday": "föstudagur", "Saturday": "laugardagur", "Sunday": "sunnudagur"
}

# The .ics file generated by Canvas
URL = "https://canvas.harvard.edu/feeds/calendars/user_NOQogScFrdtBPeSdI1gIbpScSjCBFTuHYcdNf8W1.ics"

def get_icelandic_date(dt):
    """Converts a Python date object into an Icelandic string."""
    day_name = DAYS_IS[dt.strftime("%A")]
    month_name = MONTHS_IS[dt.month]
    return f"{day_name} {dt.day}. {month_name}"

def extract_and_print(raw_ics):
    events = raw_ics.split("BEGIN:VEVENT")

    for event in events:
        if "SUMMARY:" in event and "DTSTART" in event:
            # Extract the full summary line
            summary_line = event.split("SUMMARY:")[1].split("\n")[0].strip()

            # Split the summary into Assignment and Course
            course = "Almennt" # Default if no brackets found
            assignment = summary_line

            if "[" in summary_line:
                # Split from the right at the first '[' encountered
                parts = summary_line.rsplit("[", 1)
                assignment = parts[0].strip()
                # Remove the closing ']' from the course name
                course = parts[1].replace("]", "").strip()

            # Extract date parts
            date_raw = event.split("DTSTART")[1].split(":")[1][:8]

            try:
                y, m, d = int(date_raw[0:4]), int(date_raw[4:6]), int(date_raw[6:8])
                py_date = date(y, m, d)
                is_date = get_icelandic_date(py_date)

                # Final Print Format: Date | Course: Assignment
                print(f"{is_date} \n{course}: {assignment}\n")
            except:
                continue

def main():
    print("Connecting to Canvas...")
    req = urllib.request.Request(URL, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req) as response:
        raw_text = response.read().decode('utf-8')

    print("--- ASSIGNMENTS FOUND ---")
    extract_and_print(raw_text)

if __name__ == "__main__":
    main()
